# Generated by Django 5.2.10 on 2026-02-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('pending_carrier', 'Đang chờ đơn vị vận chuyển'), ('picked_up', 'Đã lấy hàng'), ('in_transit', 'Đang giao'), ('delivered', 'Đã giao')], default='pending_carrier', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
